/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NotificationListItem: typeof import('./src/components/ui/NotificationListItem.vue')['default']
    NotificationsList: typeof import('./src/components/ui/NotificationsList.vue')['default']
    NotificationsListItem: typeof import('./src/components/ui/NotificationsListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAvatar: typeof import('./src/components/ui/TheAvatar.vue')['default']
    TheBadge: typeof import('./src/components/ui/TheBadge.vue')['default']
    TheButton: typeof import('./src/components/ui/TheButton.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheIcon: typeof import('./src/components/ui/TheIcon.vue')['default']
    TheLoader: typeof import('./src/components/ui/TheLoader.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    TheSpinner: typeof import('./src/components/ui/TheSpinner.vue')['default']
    TheTable: typeof import('./src/components/ui/TheTable.vue')['default']
  }
}
